export interface JobRequirement {
  id: string;
  title: string;
  category: string;
  requiredSkills: string[];
  description: string;
  experienceLevel: string;
  salaryRange: string;
  linkedinUrl: string;
  naukriUrl: string;
  internshalaUrl: string;
}

export const JOB_REQUIREMENTS: JobRequirement[] = [
  {
    id: 'software-engineer',
    title: 'Software Engineer',
    category: 'Software Engineering',
    requiredSkills: ['Data Structures & Algorithms', 'System Design', 'Java', 'Python', 'C++', 'SQL', 'Git', 'OOP', 'REST API', 'Docker', 'Kubernetes', 'CI/CD'],
    description: 'Design robust backend algorithms, data structures, enterprise applications, and APIs.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹8,00,000 - ₹16,00,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Software%20Engineer',
    naukriUrl: 'https://www.naukri.com/software-engineer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/software-development-jobs',
  },
  {
    id: 'data-analyst',
    title: 'Data Analyst',
    category: 'AI & Data Science',
    requiredSkills: ['SQL', 'Python', 'Excel', 'Tableau', 'PowerBI', 'Data Visualization', 'Pandas', 'Statistics', 'BigQuery', 'Data Warehousing', 'ETL Pipelines'],
    description: 'Transform complex business datasets into actionable insights using SQL queries and visual dashboards.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹6,00,000 - ₹12,00,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Data%20Analyst',
    naukriUrl: 'https://www.naukri.com/data-analyst-jobs',
    internshalaUrl: 'https://internshala.com/jobs/data-analytics-jobs',
  },
  {
    id: 'ml-engineer',
    title: 'Machine Learning Engineer',
    category: 'AI & Data Science',
    requiredSkills: ['Python', 'Machine Learning', 'PyTorch', 'TensorFlow', 'Scikit-Learn', 'Pandas', 'NumPy', 'Linear Algebra', 'Statistics', 'MLOps', 'Model Deployment', 'CUDA Optimization'],
    description: 'Develop predictive models, neural networks, ML pipelines, and production inference APIs.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹9,00,000 - ₹18,00,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Machine%20Learning%20Engineer',
    naukriUrl: 'https://www.naukri.com/machine-learning-engineer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/machine-learning-jobs',
  },
  {
    id: 'robotics-engineer',
    title: 'Robotics Engineer',
    category: 'Robotics & Mechatronics',
    requiredSkills: ['C++', 'Python', 'ROS (Robot Operating System)', 'Control Systems', 'Kinematics', 'Microcontrollers', 'OpenCV', 'CAD', 'SLAM (Localization)', 'Gazebo Simulation'],
    description: 'Design autonomous robot control algorithms, ROS nodes, computer vision navigation, and sensor actuators.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹7,50,000 - ₹15,00,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Robotics%20Engineer',
    naukriUrl: 'https://www.naukri.com/robotics-engineer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/robotics-jobs',
  },
  {
    id: 'web-developer',
    title: 'Web Developer',
    category: 'Software Engineering',
    requiredSkills: ['HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'Tailwind', 'Git', 'REST API', 'Next.js', 'GraphQL', 'Core Web Vitals'],
    description: 'Build modern responsive websites, front-end user interfaces, and full stack web services.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹6,50,000 - ₹13,00,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Web%20Developer',
    naukriUrl: 'https://www.naukri.com/web-developer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/web-development-jobs',
  },
  {
    id: 'data-scientist',
    title: 'Data Scientist',
    category: 'AI & Data Science',
    requiredSkills: ['Python', 'R', 'SQL', 'Machine Learning', 'Deep Learning', 'Statistics', 'Pandas', 'Data Mining', 'Apache Spark', 'A/B Testing', 'Big Data Analytics'],
    description: 'Solve complex business problems using advanced statistical modeling, AI algorithms, and big data.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹9,50,000 - ₹19,00,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Data%20Scientist',
    naukriUrl: 'https://www.naukri.com/data-scientist-jobs',
    internshalaUrl: 'https://internshala.com/jobs/data-science-jobs',
  },
  {
    id: 'devops-engineer',
    title: 'DevOps Engineer',
    category: 'Infrastructure & Cloud',
    requiredSkills: ['Linux', 'Docker', 'Kubernetes', 'AWS', 'CI/CD', 'Terraform', 'Git', 'Bash Shell', 'Ansible', 'Prometheus & Grafana', 'Helm Charts'],
    description: 'Automate build pipelines, containerize applications, manage cloud infrastructure, and ensure uptime.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹8,00,000 - ₹16,00,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=DevOps%20Engineer',
    naukriUrl: 'https://www.naukri.com/devops-engineer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/devops-jobs',
  },
  {
    id: 'embedded-engineer',
    title: 'Embedded Systems Engineer',
    category: 'Hardware & Firmware',
    requiredSkills: ['C', 'C++', 'Microcontrollers', 'RTOS', 'ARM Architecture', 'Circuit Design', 'Firmware', 'Embedded Linux', 'CAN Bus Protocol', 'Device Drivers'],
    description: 'Write low-level C/C++ firmware code for IoT hardware, microcontrollers, and real-time systems.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹6,50,000 - ₹13,50,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Embedded%20Systems%20Engineer',
    naukriUrl: 'https://www.naukri.com/embedded-systems-jobs',
    internshalaUrl: 'https://internshala.com/jobs/embedded-systems-jobs',
  },
  {
    id: 'mechanical-engineer',
    title: 'Mechanical Engineer',
    category: 'Core Engineering',
    requiredSkills: ['SolidWorks', 'AutoCAD', 'Thermodynamics', 'Fluid Mechanics', 'ANSYS', 'FEA', 'Manufacturing', 'GD&T', 'Computational Fluid Dynamics (CFD)', 'CAM Machining'],
    description: 'Design mechanical components, 3D CAD assemblies, thermal systems, and finite element stress analysis.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹5,50,000 - ₹11,50,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Mechanical%20Engineer',
    naukriUrl: 'https://www.naukri.com/mechanical-engineer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/mechanical-engineering-jobs',
  },
  {
    id: 'ai-engineer',
    title: 'AI Engineer',
    category: 'AI & Data Science',
    requiredSkills: ['Python', 'Deep Learning', 'NLP', 'Computer Vision', 'PyTorch', 'TensorFlow', 'Generative AI', 'Transformers', 'LangChain', 'LLMs', 'Vector Databases', 'Model Fine-Tuning (LoRA)'],
    description: 'Develop Generative AI applications, Large Language Models (LLMs), RAG pipelines, and vision models.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹10,00,000 - ₹22,00,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=AI%20Engineer',
    naukriUrl: 'https://www.naukri.com/ai-engineer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/artificial-intelligence-jobs',
  },
  {
    id: 'civil-engineer',
    title: 'Civil Engineer',
    category: 'Core Engineering',
    requiredSkills: ['AutoCAD', 'STAAD Pro', 'Structural Analysis', 'Surveying', 'Concrete Technology', 'Geotechnical', 'Revit', 'ETABS Software', 'BIM Coordination'],
    description: 'Plan infrastructure projects, structural designs, surveying calculations, and construction management.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹5,00,000 - ₹10,50,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Civil%20Engineer',
    naukriUrl: 'https://www.naukri.com/civil-engineer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/civil-engineering-jobs',
  },
  {
    id: 'electrical-engineer',
    title: 'Electrical Engineer',
    category: 'Core Engineering',
    requiredSkills: ['MATLAB', 'Simulink', 'Circuit Theory', 'Power Systems', 'Control Systems', 'PLC Programming', 'PCB Design', 'SCADA Automation', 'High Voltage Protection'],
    description: 'Design electrical power systems, control circuits, automation PLCs, and motor drives.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹5,50,000 - ₹11,50,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=Electrical%20Engineer',
    naukriUrl: 'https://www.naukri.com/electrical-engineer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/electrical-engineering-jobs',
  },
  {
    id: 'iot-engineer',
    title: 'IoT Engineer',
    category: 'Hardware & Network',
    requiredSkills: ['Embedded C', 'Python', 'Arduino', 'Raspberry Pi', 'MQTT', 'Zigbee', 'Wireless Sensors', 'IoT Cloud Platforms', 'LoRaWAN Protocol', 'Edge AI'],
    description: 'Develop connected smart IoT devices, wireless sensor networks, and edge cloud telemetry dashboards.',
    experienceLevel: 'Entry Level (0-2 Yrs)',
    salaryRange: '₹6,00,000 - ₹12,50,000 PA',
    linkedinUrl: 'https://www.linkedin.com/jobs/search/?keywords=IoT%20Engineer',
    naukriUrl: 'https://www.naukri.com/iot-engineer-jobs',
    internshalaUrl: 'https://internshala.com/jobs/iot-jobs',
  },
];
